# Pastel Black Theme
# Copyright: "Gokay BURUC"
# Theme Creator :https://github.com/gokayburuc
# Created: 2025-11-07

# TODO: add screenshot 
# TODO: add readme

# Attribute Highight 
'attribute' = { fg = 'pink-light' }

# Constructor Highlight
'constructor' = { fg = 'green-dark', modifiers = ['italic'] }
# Constant Highlight
'constant' = { fg = 'green-light', modifiers = ['bold'] }
# 'constant.builtin' = { fg = '' }
# 'constant.builtin.boolean' = { fg = 'yellow' }
# 'constant.character' = {fg = 'cyan'}
# 'constant.character.escape' = {}
# 'constant.numeric' = { fg = 'orange' }
# 'constant.numeric.float' = {}
# 'constant.numeric.integer' = {}

# String Highlights
'string' = { fg = 'green', modifiers = ['italic'] }
# 'string.regexp' = {}
# 'string.special' = {}
# 'string.special.path' = {}
# 'string.special.url' = {}
# 'string.special.symbol' = {}

# Comment Highlights
# 'comment.block.documentation' = { fg = 'green', modifiers = ['italic'] }
# 'comment.block' = { fg = 'green', modifiers = ['italic'] }
'comment' = { fg = 'gray', modifiers = ['italic'] }
# 'comment.line' = {}
# 'comment.line.documentation' = {}
# 'comment.unused' = {}

# Variable Highlights
'variable' = { fg = 'pink-dark', modifiers = ['italic', 'bold'] }
# 'variable.builtin' = { fg = 'yellow' }
# 'variable.parameter' = { fg = 'white' }
# 'variable.other' = { fg = 'cyan' }
'variable.other.member' = { fg = 'pink-dark', modifiers = ['italic','bold'] }
'variable.other.member.private' = { fg = 'pink-dark', modifiers = ['italic','bold']}

# Label Highlights
'label' = { fg = 'yellow', modifiers = [ 'italic'] }

# Punctuation Highlights
'punctuation' = { fg = 'yellow-light', modifiers = ['bold'] }
'punctuation.bracket' = { fg = 'yellow-light', modifiers=['bold']}
'punctuatioblueimiter' = { fg = 'yellow-light', modifiers = ['bold'] }
'punctuatiobluecial' = { fg = 'yellow-light' }

# Keyword Hblueghts
'keyword' = { fg = 'blue-light', modifiers = ['bold', 'italic'] }
'keyword.control' = {fg = 'blue-light', modifiers = ['bold']}
# 'keyword.control.conditional' = {}
# 'keyword.control.repeat' = {}
'keyword.control.import' = { fg = 'blue-light', modifiers = ['italic','bold']}
# 'keyword.control.return' = {}
# 'keyword.control.exception' = {}

# Operator Highlights
'operator' = { fg = 'yellow', modifiers = ['bold'] }

# Directive Highlights (and,or,not)
'directive' = { fg = 'yellow' }

# Special Highlights 
'special' = { fg = 'yellow' }

# Namespace Highlights
'namespace' = { fg = 'blue', modifiers = ['italic'] }

# Function Highlights 
'function' = { fg = 'blue-dark', modifiers = ['bold', 'italic'] }
'function.builtin' = { fg = 'blue-dark', modifiers = ['bold','italic'] }
'function.method' = { fg = 'blue-dark' , modifiers= ['italic']}
'function.method.private' = { fg = 'blue-dark' }
'function.macro' = {fg = 'blue-dark'}
'function.special' = {fg = 'blue-dark'}

# Tag Highlights 
'tag' = { fg = 'blue', modifiers = ['italic','bold'] }

# Type Highlights 
'type' = { fg = 'green-dark', modifiers = ['italic']}
# 'type.bultin' = { fg = 'pink', modifiers=['bold'] }
# 'type.parameter' = { fg = 'green' }
# 'type.enum' = { fg = 'green' }
# 'type.enum.variant' = { fg = 'green' }

# Markup Highlights 
'markup.bold' = { fg = 'blue', modifiers = ['bold'] }
'markup.italic' = { fg = 'blue-light', modifiers = ['italic'] }
# 'markup.strikethrough' = { modifiers = ['crossed_out'] }
'markup.heading' = { fg = 'pink', modifiers = ['bold'] }
# 'markup.heading.marker' = { fg = 'pink' }
# 'markup.heading.1' = { fg = 'pink' }
# 'markup.heading.2' = { fg = 'pink' }
# 'markup.heading.3' = { fg = 'pink' }
# 'markup.heading.4' = { fg = 'pink' }
# 'markup.heading.5' = { fg = 'pink' }
# 'markup.heading.6' = { fg = 'pink' }
# 'markup.link' = { fg = 'pink700' }
'markup.link.url' = { fg = 'yellow-dark' }
'markup.link.text' = { fg = 'yellow-light' }
'markup.link.label' = { fg = 'yellow-dark' }
'markup.list' = { fg = 'pink-light', modifiers = ['bold'] }
# 'markup.list.unnumbepink' = { fg = 'pink' }
# 'markup.list.numbepink' = { fg = 'pink' }
# 'markup.list.checked' = { fg = 'pink' }
# 'markup.list.unchecked' = { fg = 'pink' }
'markup.quote' = { fg = 'blue-light', bg = 'bg01', modifiers = ['italic'] }
'markup.raw' = { fg = 'blue-dark'}
# 'markup.raw.block' = { fg = 'green', bg = 'bg' }
# 'markup.raw.inline' = { fg = 'green', bg = 'bg' }

# Diff Highlights
# 'diff.delta.conflict' = { fg = 'pink' }
'diff.delta' = { fg = 'yellow' }
# 'diff.delta.gutter' = { fg = 'white' }
# 'diff.delta.moved' = { fg = 'cyan' }
'diff.minus' = { fg = 'pink' }
# 'diff.minus.gutter' = { fg = 'pink' }
'diff.plus' = { fg = 'blue-light' }
# 'diff.plus.gutter' = { fg = 'green' }


# ========================== INTERFACE ========================= 

# Interface Configs
# Markup Interface
# 'markup' = {}
# 'markup.normal' = {}
# 'markup.completion' = {}
# 'markup.hover' = {}
# 'markup.heading.completion' = {}
# 'markup.heading.hover' = {}
# 'markup.raw.inline.completion' = {}
# 'markup.raw.inline.hover'= {}

# User Interface (UI) Configs 
'ui.background' = { bg = 'bg' }
'ui.bufferline' = { fg = 'fg', bg = 'bg-01' }
'ui.bufferline.active' = { fg = 'yellow', bg = 'bg-01' }
# 'ui.bufferline.background' = { bg = 'bg01' }
'ui.cursor' = { bg = 'blue-light', fg = 'yellow-light' }
# 'ui.cursor.insert' = { bg = 'orange', fg = 'bg-alt' }
# 'ui.cursor.match' = { fg = 'pink', modifiers = ['bold'] }
# 'ui.cursor.normal' = { bg = 'orange', fg = 'bg-alt' }
# 'ui.cursor.primary' = { bg = 'orange', fg = 'bg-alt' }
# 'ui.cursor.primary.insert' = { bg = 'orange', fg = 'bg-alt' }
# 'ui.cursor.primary.normal' = { bg = 'orange', fg = 'bg-alt' }
# 'ui.cursor.primary.select' = { bg = 'orange', fg = 'bg-alt' }
# 'ui.cursor.select' = { bg = 'orange', fg = 'bg-alt' }
# 'ui.cursorcolumn.primary' = {}
# 'ui.cursorcolumn.secondary' = {}
# 'ui.cursorline' = { bg = 'bg-alt' }
# 'ui.cursorline.primary' = { bg = 'bg-alt' }
# 'ui.cursorline.secondary' = { bg = 'bg-alt' }
# 'ui.debug.active' = {}
# 'ui.debug.breakpoint' = {}
# 'ui.gutter' = { fg = 'white' }
# 'ui.gutter.selected' = {}
'ui.help' = { fg = 'fg', bg = 'bg02' }
'ui.highlight' = { fg = 'fg', bg = 'bg-01' }
'ui.highlight.frameline' = { fg = 'fg', bg = 'bg-02' }
'ui.linenr' = { fg = 'yellow-light', bg = 'bg' }
'ui.linenr.selected' = { fg = 'yellow', bg = 'bg', modifiers = ['bold'] }
'ui.menu' = { fg = 'fg', bg = 'bg-01' }
'ui.menu.scroll' = { fg = 'bg-02' }
'ui.menu.selected' = { bg = 'bg-03', fg = 'fg' }
# 'ui.picker.header' = {}
# 'ui.picker.header.column' = {}
# 'ui.picker.header.column.active' = {}
'ui.popup' = { bg = 'bg-01', fg = 'fg' }
'ui.popup.info' = {fg ='fg', bg = 'bg', modifiers=['bold'] }
'ui.selection' = { bg = 'blue-dark' }
# 'ui.selection.primary' = { bg = 'bg02' }
'ui.statusline' = { fg = 'fg', bg = 'bg-01' }
# 'ui.statusline.inactive' = { bg = 'base03' }
# 'ui.statusline.insert' = { bg = 'base03' }
# 'ui.statusline.normal' = { bg = 'base03' }
# 'ui.statusline.select' = { bg = 'base03' }
# 'ui.statusline.seperator' = { bg = 'base03' }
'ui.text' = { fg = 'fg' }
# 'ui.text.directory' = { fg = 'fg' }
# 'ui.text.focus' = { bg = 'bg-alt', fg = 'fg' }
# 'ui.text.inactive' = { fg = 'fg' }
# 'ui.text.info' = { fg = 'fg' }
# 'ui.virtual.indent-guide' = { fg = 'bg02' }
# 'ui.virtual.inlay-hint' = { fg = 'bg02' }
# 'ui.virtual.inlay-hint.parameter' = { fg = 'bg02' }
# 'ui.virtual.inlay-hint.type' = { fg = 'bg02' }
# 'ui.virtual.jump-label' = { fg = 'bg02' }
'ui.virtual.ruler' = { bg = 'bg-01' }
# 'ui.virtual.whitespace' = { fg = 'bg02' }
# 'ui.virtual.wrap' = { fg = 'bg02' }
'ui.window' = { fg = 'gray' }

'error' = { fg = 'pink', modifiers = ['bold'] }
'hint' = { fg = 'blue-light', modifiers = ['bold'] }
'info' = { fg = 'fg', modifiers = ['bold'] }
'warning' = { fg = 'pink-light', modifiers = ['bold']}

# 'diagnostic' = {}
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }
'diagnostic.error' = { underline = { color = 'pink', style = "curl" } }
'diagnostic.hint' = { underline = { color = 'pink-light', style = "curl" } }
'diagnostic.info' = { underline = { color = 'blue-light', style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
'diagnostic.warning' = { underline = { color = 'yellow', style = "curl" } }
# 'tabstop' = {}




[palette]
bg='#000000'
fg='#D9D9D9'
yellow='#DBD62E'
yellow-dark='#AFAD00'
yellow-light='#FFFF5D'
blue='#33A9C9'
blue-light='#66D2F3'
blue-dark='#0081A0'
gray='#49666E'
pink='#FD94B4'
pink-dark='#D16C8C'
pink-light='#FFBEDE'
green='#B2EA59'
green-dark='#88C02D'
green-light='#D8FF7E'
bg-01='#171717'
bg-02='#262626'
bg-03='#363636'
bg-04='#474747'
